# Generated by Django 3.0.5 on 2020-10-27 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='username',
            field=models.ManyToManyField(related_name='team_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='team_pk',
            field=models.ManyToManyField(related_name='match_team', to='match.Team'),
        ),
        migrations.AddField(
            model_name='locations',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Match'),
        ),
    ]
