# Generated by Django 3.0.5 on 2020-11-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
