# Generated by Django 3.0.5 on 2020-11-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20201111_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='won_team',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
