# Generated by Django 3.0.5 on 2020-11-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_match_won_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='false_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='true_result',
            field=models.BooleanField(default=False),
        ),
    ]
