# Generated by Django 3.0.5 on 2020-10-27 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Match'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_pk',
            field=models.ManyToManyField(related_name='match_team', to='match.Team'),
        ),
    ]
