# Generated by Django 3.0.5 on 2020-10-29 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20201027_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team_pk',
        ),
        migrations.RemoveField(
            model_name='team',
            name='username',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
