# Generated by Django 3.0.5 on 2020-11-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforematch',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
