# Generated by Django 3.0.5 on 2020-11-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforematch',
            name='sports_name',
            field=models.CharField(max_length=20),
        ),
    ]
