# Generated by Django 3.0.5 on 2020-10-29 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='basketball_lose',
        ),
        migrations.RemoveField(
            model_name='user',
            name='basketball_win',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bowling_average',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bowling_lose',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bowling_win',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pool_average',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pool_lose',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pool_win',
        ),
        migrations.RemoveField(
            model_name='user',
            name='soccer_lose',
        ),
        migrations.RemoveField(
            model_name='user',
            name='soccer_win',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tennis_lose',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tennis_win',
        ),
    ]
