# Generated by Django 3.0.5 on 2020-11-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201103_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforematch',
            name='gu',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
